### ISSUE TITLE
Missing third-party directory referred to from README file

### ISSUE THREAD

**Issue by tomersagi** [HewlettPackard/sparkle#1]
in the alps folder the README.md file states that the source code for external libraries can be found in the third-party folder. No such folder exists. 
Also the package names for the dependenciesare given for L4TM (?) or maybe Debian, but for those of us running RHEL 7 they don't work.

**Comment by venkyn2** [comment]
Many modules are evolving at HPE so, you don't find them here, take a  look at https://github.com/FabricAttachedMemory/
