### ISSUE TITLE
Which "alps" should I commit?

### ISSUE THREAD

**Issue by Y-Ymb** [HewlettPackard/sparkle#2]
Description
--
I tried to build sparkle on FAME environment, so I used [hvolos/alps](https://github.com/hvolos/alps) repository for compiling with `-DTARGET_ARCH_MEM=NV-NCC_FAM` option.
And then I found a bug which is common to both repositories.

Question
-- 
Which repository I should report bug or create Pull requests?
(or both repositories?)

**Comment by ssinghal53** [comment]
You can submit them to both.
